export const resources = [
  {
    key: "autores",
    label: "Autores",
    path: "/autores",
    idFields: ["idAutor"],
    supportsUpdate: true,
    fields: [{ name: "nomeAutor", label: "Nome do Autor", type: "text" }],
  },
  {
    key: "clientes",
    label: "Clientes",
    path: "/clientes",
    idFields: ["idCliente"],
    supportsUpdate: true,
    fields: [
      { name: "nomeCliente", label: "Nome", type: "text" },
      { name: "cpf", label: "CPF", type: "text" },
      { name: "dataNascimento", label: "Nascimento", type: "date" },
      { name: "telefone", label: "Telefone", type: "text" },
      { name: "email", label: "Email", type: "text" },
      { name: "endereco", label: "Endereco", type: "text" },
      { name: "bloqueado", label: "Bloqueado", type: "boolean" },
      { name: "tentativasLogin", label: "Tentativas", type: "number" },
      { name: "emailConfirmado", label: "Email Confirmado", type: "boolean" },
      { name: "senhaCliente", label: "Senha", type: "text", createOnly: true },
    ],
  },
  {
    key: "estoque",
    label: "Estoque",
    path: "/estoque",
    idFields: ["idEstoque"],
    supportsUpdate: true,
    filters: [
      { name: "idLivro", label: "Filtrar por Livro", type: "number" },
      { name: "disponivel", label: "Somente Disponiveis", type: "boolean" },
    ],
    fields: [
      { name: "idLivro", label: "Livro", type: "number", lookup: { resource: "livros", labelField: "nomeLivro" } },
      { name: "quantidadeTotal", label: "Total", type: "number" },
      { name: "quantidadeReservada", label: "Reservada", type: "number" },
      { name: "quantidadeEmprestada", label: "Emprestada", type: "number" },
      { name: "quantidadeDanificada", label: "Danificada", type: "number" },
      { name: "estoqueMinimo", label: "Minimo", type: "number" },
    ],
  },
  {
    key: "fotos",
    label: "Fotos",
    path: "/fotos",
    idFields: ["idFoto"],
    supportsUpdate: true,
    fields: [
      { name: "idLivro", label: "Livro", type: "number", lookup: { resource: "livros", labelField: "nomeLivro" } },
      { name: "foto", label: "URL da Foto", type: "text" },
    ],
  },
  {
    key: "funcionarios",
    label: "Funcionarios",
    path: "/funcionarios",
    idFields: ["idFuncionario"],
    supportsUpdate: true,
    fields: [
      { name: "nome", label: "Nome", type: "text" },
      { name: "email", label: "Email", type: "text" },
      { name: "perfil", label: "Perfil", type: "text", options: [
        { value: "A", label: "Administrador" },
        { value: "G", label: "Gerente" },
        { value: "F", label: "Funcionário" },
      ] },
      { name: "senha", label: "Senha", type: "text", createOnly: true },
    ],
  },
  {
    key: "generos",
    label: "Generos",
    path: "/generos",
    idFields: ["idGenero"],
    supportsUpdate: true,
    fields: [{ name: "nomeGenero", label: "Nome do Genero", type: "text" }],
  },
  {
    key: "historico-cliente",
    label: "Historico de Cliente",
    path: "/historico-cliente",
    idFields: ["idHistorico"],
    supportsUpdate: false,
    fields: [
      { name: "idCliente", label: "Cliente", type: "number", lookup: { resource: "clientes", labelField: "nomeCliente" } },
      { name: "campoAlterado", label: "Campo Alterado", type: "text" },
      { name: "valorAntigo", label: "Valor Antigo", type: "text" },
      { name: "valorNovo", label: "Valor Novo", type: "text" },
      { name: "dataAlteracao", label: "Data Alteracao", type: "datetime-local" },
    ],
  },
  {
    key: "livro-autor",
    label: "Livro x Autor",
    path: "/livro-autor",
    idFields: ["idLivro", "idAutor"],
    supportsUpdate: false,
    fields: [
      { name: "idLivro", label: "Livro", type: "number", lookup: { resource: "livros", labelField: "nomeLivro" } },
      { name: "idAutor", label: "Autor", type: "number", lookup: { resource: "autores", labelField: "nomeAutor" } },
    ],
  },
  {
    key: "livro-genero",
    label: "Livro x Genero",
    path: "/livro-genero",
    idFields: ["idLivro", "idGenero"],
    supportsUpdate: false,
    fields: [
      { name: "idLivro", label: "Livro", type: "number", lookup: { resource: "livros", labelField: "nomeLivro" } },
      { name: "idGenero", label: "Genero", type: "number", lookup: { resource: "generos", labelField: "nomeGenero" } },
    ],
  },
  {
    key: "livros",
    label: "Livros",
    path: "/livros",
    idFields: ["idLivro"],
    supportsUpdate: true,
    filters: [
      { name: "nome", label: "Filtrar por Nome", type: "text" },
      { name: "editora", label: "Filtrar por Editora", type: "text" },
      { name: "ano", label: "Filtrar por Ano", type: "number" },
    ],
    fields: [
      { name: "nomeLivro", label: "Nome", type: "text" },
      { name: "isnb", label: "ISBN", type: "text" },
      { name: "editora", label: "Editora", type: "text" },
      { name: "ano", label: "Ano", type: "number" },
      { name: "sinopse", label: "Sinopse", type: "text" },
      { name: "localizacaoFisica", label: "Localizacao", type: "text" },
    ],
  },
  {
    key: "logs",
    label: "Logs",
    path: "/logs",
    idFields: ["idLog"],
    supportsUpdate: false,
    fields: [
      { name: "idCliente", label: "Cliente", type: "number", lookup: { resource: "clientes", labelField: "nomeCliente" } },
      { name: "idFuncionario", label: "Funcionario", type: "number", lookup: { resource: "funcionarios", labelField: "nome" } },
      { name: "acao", label: "Acao", type: "text" },
      { name: "dataAcao", label: "Data Acao", type: "datetime-local" },
      { name: "ip", label: "IP", type: "text" },
    ],
  },
  {
    key: "movimentacao-estoque",
    label: "Movimentacao de Estoque",
    path: "/movimentacao-estoque",
    idFields: ["idMovimentacao"],
    supportsUpdate: false,
    fields: [
      { name: "idLivro", label: "Livro", type: "number", lookup: { resource: "livros", labelField: "nomeLivro" } },
      { name: "tipoMovimentacao", label: "Tipo (E/P/A/X)", type: "text", options: [
        { value: "E", label: "E — Entrada" },
        { value: "P", label: "P — Perda" },
        { value: "A", label: "A — Ajuste" },
        { value: "X", label: "X — Danificado" },
      ] },
      { name: "quantidade", label: "Quantidade", type: "number" },
      { name: "dataMovimentacao", label: "Data", type: "date" },
      { name: "motivo", label: "Motivo", type: "text" },
    ],
  },
  {
    key: "multas",
    label: "Multas",
    path: "/multas",
    idFields: ["idMulta"],
    supportsUpdate: true,
    filters: [
      { name: "idReserva", label: "Filtrar por Reserva", type: "number" },
      { name: "status", label: "Filtrar por Status", type: "text" },
    ],
    fields: [
      { name: "idReserva", label: "Reserva", type: "number", lookup: { resource: "reservas", labelField: "codigoReserva", idField: "idReserva" } },
      { name: "valorMulta", label: "Valor", type: "decimal" },
      { name: "dataMulta", label: "Data da Multa", type: "date" },
      { name: "statusMulta", label: "Status", type: "text", options: [
        { value: "pendente",  label: "Pendente" },
        { value: "pago",      label: "Pago" },
        { value: "cancelado", label: "Cancelado" },
      ] },
      { name: "dataPagamento", label: "Data de Pagamento", type: "date" },
    ],
  },
  {
    key: "reservas",
    label: "Reservas",
    path: "/reservas",
    idFields: ["idReserva"],
    supportsUpdate: true,
    filters: [
      { name: "idCliente", label: "Filtrar por Cliente", type: "number" },
      { name: "idLivro", label: "Filtrar por Livro", type: "number" },
      { name: "status", label: "Filtrar por Status", type: "text" },
    ],
    fields: [
      { name: "idCliente", label: "Cliente", type: "number", lookup: { resource: "clientes", labelField: "nomeCliente" } },
      { name: "idLivro", label: "Livro", type: "number", lookup: { resource: "livros", labelField: "nomeLivro" } },
      { name: "idFuncionarioRetirada", label: "Funcionario Retirada", type: "number", lookup: { resource: "funcionarios", labelField: "nome" } },
      { name: "idFuncionarioDevolucao", label: "Funcionario Devolucao", type: "number", lookup: { resource: "funcionarios", labelField: "nome" } },
      { name: "dataReserva", label: "Data Reserva", type: "date" },
      { name: "dataLimiteRetirada", label: "Limite Retirada", type: "date" },
      { name: "dataRetirada", label: "Data Retirada", type: "date" },
      { name: "dataPrevistaDevolucao", label: "Prevista Devolucao", type: "date" },
      { name: "dataDevolucao", label: "Data Devolucao", type: "date" },
      { name: "statusReserva", label: "Status", type: "text", options: [
        { value: "reservado",  label: "Reservado" },
        { value: "emprestado", label: "Emprestado" },
        { value: "devolvido",  label: "Devolvido" },
        { value: "cancelado",  label: "Cancelado" },
        { value: "atrasado",   label: "Atrasado" },
      ] },
      { name: "codigoReserva", label: "Codigo", type: "text", autoGenerate: true },
    ],
  },
];

export function getResourceByKey(key) {
  return resources.find((resource) => resource.key === key);
}
